# Generated by Django 3.0.11 on 2020-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (3, 'unspecified')], default=4, null=True),
        ),
    ]
