# Generated by Django 3.0.11 on 2020-12-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20201124_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdescription',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='appointment.Appointment'),
        ),
    ]
