# Generated by Django 3.0.11 on 2020-12-03 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointment.Appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointment.Appointment'),
        ),
        migrations.AlterField(
            model_name='visitdescription',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointment.Appointment'),
        ),
    ]
